PREFIX gi2mo: <http://purl.org/gi2mo/ns#>
PREFIX inov:<http://purl.org/innovonto/types/#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?linkedResource (COUNT(?linkedResource) as ?resourceCount)
WHERE {
  ?idea a gi2mo:Idea;
        inov:hasAnnotation ?annotation.
  ?annotation inov:annotationState "approved";
              inov:hasResourceCandidate ?resourceCandidate.
  ?resourceCandidate inov:selected ?selected.
  ?resourceCandidate inov:hasLinkedResource ?linkedResource.
  FILTER (?selected = "true"^^xsd:boolean)
}
GROUP BY ?linkedResource
ORDER BY DESC(?resourceCount)