PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX gi2mo: <http://purl.org/gi2mo/ns#>
PREFIX inov:<http://purl.org/innovonto/types/#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?idea
WHERE {
  ?idea a gi2mo:Idea.
  ?idea inov:hasAnnotation ?annotation.
  ?annotation inov:annotationState "approved".
  ?annotation inov:hasResourceCandidate ?resourceCandidate.
  ?resourceCandidate inov:selected ?selected.
  ?resourceCandidate inov:hasLinkedResource ?linkedResource.
  ?linkedResource rdfs:subClassOf* ?marker
  FILTER (?selected = "true"^^xsd:boolean)
}